/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as CommandRouteImport } from './routes/command'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as EngineeringRouteImport } from './routes/engineering'
import { Route as ExecutiveRouteImport } from './routes/executive'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as RoadmapsRouteImport } from './routes/roadmaps'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EngineeringIndexRouteImport } from './routes/engineering.index'
import { Route as EngineeringCheckpointsRouteImport } from './routes/engineering.checkpoints'
import { Route as EngineeringStagesRouteImport } from './routes/engineering.stages'
import { Route as InfrastructureIndexRouteImport } from './routes/infrastructure.index'
import { Route as InfrastructureTopologyRouteImport } from './routes/infrastructure.topology'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations.index'
import { Route as OrganizationsOrganizationIdRouteImport } from './routes/organizations.$organizationId'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsProductKeyRouteImport } from './routes/products.$productKey'
import { Route as ReleasesIndexRouteImport } from './routes/releases.index'
import { Route as ReleasesReleaseIdRouteImport } from './routes/releases.$releaseId'
import { Route as RepositoriesIndexRouteImport } from './routes/repositories.index'
import { Route as RepositoriesRepositoryIdRouteImport } from './routes/repositories.$repositoryId'
import { Route as WorkspacesWorkspaceKeyRouteImport } from './routes/workspaces.$workspaceKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringRoute = EngineeringRouteImport.update({
  id: '/engineering',
  path: '/engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveRoute = ExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsRoute = RoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringIndexRoute = EngineeringIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EngineeringRoute,
} as any)
const EngineeringCheckpointsRoute = EngineeringCheckpointsRouteImport.update({
  id: '/checkpoints',
  path: '/checkpoints',
  getParentRoute: () => EngineeringRoute,
} as any)
const EngineeringStagesRoute = EngineeringStagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => EngineeringRoute,
} as any)
const InfrastructureIndexRoute = InfrastructureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InfrastructureRoute,
} as any)
const InfrastructureTopologyRoute = InfrastructureTopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => InfrastructureRoute,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationsRoute,
} as any)
const OrganizationsOrganizationIdRoute =
  OrganizationsOrganizationIdRouteImport.update({
    id: '/$organizationId',
    path: '/$organizationId',
    getParentRoute: () => OrganizationsRoute,
  } as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsProductKeyRoute = ProductsProductKeyRouteImport.update({
  id: '/$productKey',
  path: '/$productKey',
  getParentRoute: () => ProductsRoute,
} as any)
const ReleasesIndexRoute = ReleasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReleasesRoute,
} as any)
const ReleasesReleaseIdRoute = ReleasesReleaseIdRouteImport.update({
  id: '/$releaseId',
  path: '/$releaseId',
  getParentRoute: () => ReleasesRoute,
} as any)
const RepositoriesIndexRoute = RepositoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepositoriesRoute,
} as any)
const RepositoriesRepositoryIdRoute =
  RepositoriesRepositoryIdRouteImport.update({
    id: '/$repositoryId',
    path: '/$repositoryId',
    getParentRoute: () => RepositoriesRoute,
  } as any)
const WorkspacesWorkspaceKeyRoute = WorkspacesWorkspaceKeyRouteImport.update({
  id: '/workspaces/$workspaceKey',
  path: '/workspaces/$workspaceKey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ai': typeof AiRoute
  '/assets': typeof AssetsRoute
  '/command': typeof CommandRoute
  '/decisions': typeof DecisionsRoute
  '/documents': typeof DocumentsRoute
  '/engineering': typeof EngineeringRouteWithChildren
  '/executive': typeof ExecutiveRoute
  '/infrastructure': typeof InfrastructureRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/releases': typeof ReleasesRouteWithChildren
  '/repositories': typeof RepositoriesRouteWithChildren
  '/roadmaps': typeof RoadmapsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/engineering/checkpoints': typeof EngineeringCheckpointsRoute
  '/engineering/stages': typeof EngineeringStagesRoute
  '/infrastructure/topology': typeof InfrastructureTopologyRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRoute
  '/products/$productKey': typeof ProductsProductKeyRoute
  '/releases/$releaseId': typeof ReleasesReleaseIdRoute
  '/repositories/$repositoryId': typeof RepositoriesRepositoryIdRoute
  '/workspaces/$workspaceKey': typeof WorkspacesWorkspaceKeyRoute
  '/engineering/': typeof EngineeringIndexRoute
  '/infrastructure/': typeof InfrastructureIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/releases/': typeof ReleasesIndexRoute
  '/repositories/': typeof RepositoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ai': typeof AiRoute
  '/assets': typeof AssetsRoute
  '/command': typeof CommandRoute
  '/decisions': typeof DecisionsRoute
  '/documents': typeof DocumentsRoute
  '/executive': typeof ExecutiveRoute
  '/notifications': typeof NotificationsRoute
  '/roadmaps': typeof RoadmapsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/engineering/checkpoints': typeof EngineeringCheckpointsRoute
  '/engineering/stages': typeof EngineeringStagesRoute
  '/infrastructure/topology': typeof InfrastructureTopologyRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRoute
  '/products/$productKey': typeof ProductsProductKeyRoute
  '/releases/$releaseId': typeof ReleasesReleaseIdRoute
  '/repositories/$repositoryId': typeof RepositoriesRepositoryIdRoute
  '/workspaces/$workspaceKey': typeof WorkspacesWorkspaceKeyRoute
  '/engineering': typeof EngineeringIndexRoute
  '/infrastructure': typeof InfrastructureIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/releases': typeof ReleasesIndexRoute
  '/repositories': typeof RepositoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ai': typeof AiRoute
  '/assets': typeof AssetsRoute
  '/command': typeof CommandRoute
  '/decisions': typeof DecisionsRoute
  '/documents': typeof DocumentsRoute
  '/engineering': typeof EngineeringRouteWithChildren
  '/executive': typeof ExecutiveRoute
  '/infrastructure': typeof InfrastructureRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/releases': typeof ReleasesRouteWithChildren
  '/repositories': typeof RepositoriesRouteWithChildren
  '/roadmaps': typeof RoadmapsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/engineering/checkpoints': typeof EngineeringCheckpointsRoute
  '/engineering/stages': typeof EngineeringStagesRoute
  '/infrastructure/topology': typeof InfrastructureTopologyRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRoute
  '/products/$productKey': typeof ProductsProductKeyRoute
  '/releases/$releaseId': typeof ReleasesReleaseIdRoute
  '/repositories/$repositoryId': typeof RepositoriesRepositoryIdRoute
  '/workspaces/$workspaceKey': typeof WorkspacesWorkspaceKeyRoute
  '/engineering/': typeof EngineeringIndexRoute
  '/infrastructure/': typeof InfrastructureIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/releases/': typeof ReleasesIndexRoute
  '/repositories/': typeof RepositoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/ai'
    | '/assets'
    | '/command'
    | '/decisions'
    | '/documents'
    | '/engineering'
    | '/executive'
    | '/infrastructure'
    | '/notifications'
    | '/organizations'
    | '/products'
    | '/releases'
    | '/repositories'
    | '/roadmaps'
    | '/search'
    | '/settings'
    | '/engineering/checkpoints'
    | '/engineering/stages'
    | '/infrastructure/topology'
    | '/organizations/$organizationId'
    | '/products/$productKey'
    | '/releases/$releaseId'
    | '/repositories/$repositoryId'
    | '/workspaces/$workspaceKey'
    | '/engineering/'
    | '/infrastructure/'
    | '/organizations/'
    | '/products/'
    | '/releases/'
    | '/repositories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/ai'
    | '/assets'
    | '/command'
    | '/decisions'
    | '/documents'
    | '/executive'
    | '/notifications'
    | '/roadmaps'
    | '/search'
    | '/settings'
    | '/engineering/checkpoints'
    | '/engineering/stages'
    | '/infrastructure/topology'
    | '/organizations/$organizationId'
    | '/products/$productKey'
    | '/releases/$releaseId'
    | '/repositories/$repositoryId'
    | '/workspaces/$workspaceKey'
    | '/engineering'
    | '/infrastructure'
    | '/organizations'
    | '/products'
    | '/releases'
    | '/repositories'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/ai'
    | '/assets'
    | '/command'
    | '/decisions'
    | '/documents'
    | '/engineering'
    | '/executive'
    | '/infrastructure'
    | '/notifications'
    | '/organizations'
    | '/products'
    | '/releases'
    | '/repositories'
    | '/roadmaps'
    | '/search'
    | '/settings'
    | '/engineering/checkpoints'
    | '/engineering/stages'
    | '/infrastructure/topology'
    | '/organizations/$organizationId'
    | '/products/$productKey'
    | '/releases/$releaseId'
    | '/repositories/$repositoryId'
    | '/workspaces/$workspaceKey'
    | '/engineering/'
    | '/infrastructure/'
    | '/organizations/'
    | '/products/'
    | '/releases/'
    | '/repositories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AiRoute: typeof AiRoute
  AssetsRoute: typeof AssetsRoute
  CommandRoute: typeof CommandRoute
  DecisionsRoute: typeof DecisionsRoute
  DocumentsRoute: typeof DocumentsRoute
  EngineeringRoute: typeof EngineeringRouteWithChildren
  ExecutiveRoute: typeof ExecutiveRoute
  InfrastructureRoute: typeof InfrastructureRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OrganizationsRoute: typeof OrganizationsRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  ReleasesRoute: typeof ReleasesRouteWithChildren
  RepositoriesRoute: typeof RepositoriesRouteWithChildren
  RoadmapsRoute: typeof RoadmapsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  WorkspacesWorkspaceKeyRoute: typeof WorkspacesWorkspaceKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering': {
      id: '/engineering'
      path: '/engineering'
      fullPath: '/engineering'
      preLoaderRoute: typeof EngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive': {
      id: '/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof ExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps': {
      id: '/roadmaps'
      path: '/roadmaps'
      fullPath: '/roadmaps'
      preLoaderRoute: typeof RoadmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering/': {
      id: '/engineering/'
      path: '/'
      fullPath: '/engineering/'
      preLoaderRoute: typeof EngineeringIndexRouteImport
      parentRoute: typeof EngineeringRoute
    }
    '/engineering/checkpoints': {
      id: '/engineering/checkpoints'
      path: '/checkpoints'
      fullPath: '/engineering/checkpoints'
      preLoaderRoute: typeof EngineeringCheckpointsRouteImport
      parentRoute: typeof EngineeringRoute
    }
    '/engineering/stages': {
      id: '/engineering/stages'
      path: '/stages'
      fullPath: '/engineering/stages'
      preLoaderRoute: typeof EngineeringStagesRouteImport
      parentRoute: typeof EngineeringRoute
    }
    '/infrastructure/': {
      id: '/infrastructure/'
      path: '/'
      fullPath: '/infrastructure/'
      preLoaderRoute: typeof InfrastructureIndexRouteImport
      parentRoute: typeof InfrastructureRoute
    }
    '/infrastructure/topology': {
      id: '/infrastructure/topology'
      path: '/topology'
      fullPath: '/infrastructure/topology'
      preLoaderRoute: typeof InfrastructureTopologyRouteImport
      parentRoute: typeof InfrastructureRoute
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/organizations/$organizationId': {
      id: '/organizations/$organizationId'
      path: '/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof OrganizationsOrganizationIdRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$productKey': {
      id: '/products/$productKey'
      path: '/$productKey'
      fullPath: '/products/$productKey'
      preLoaderRoute: typeof ProductsProductKeyRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/releases/': {
      id: '/releases/'
      path: '/'
      fullPath: '/releases/'
      preLoaderRoute: typeof ReleasesIndexRouteImport
      parentRoute: typeof ReleasesRoute
    }
    '/releases/$releaseId': {
      id: '/releases/$releaseId'
      path: '/$releaseId'
      fullPath: '/releases/$releaseId'
      preLoaderRoute: typeof ReleasesReleaseIdRouteImport
      parentRoute: typeof ReleasesRoute
    }
    '/repositories/': {
      id: '/repositories/'
      path: '/'
      fullPath: '/repositories/'
      preLoaderRoute: typeof RepositoriesIndexRouteImport
      parentRoute: typeof RepositoriesRoute
    }
    '/repositories/$repositoryId': {
      id: '/repositories/$repositoryId'
      path: '/$repositoryId'
      fullPath: '/repositories/$repositoryId'
      preLoaderRoute: typeof RepositoriesRepositoryIdRouteImport
      parentRoute: typeof RepositoriesRoute
    }
    '/workspaces/$workspaceKey': {
      id: '/workspaces/$workspaceKey'
      path: '/workspaces/$workspaceKey'
      fullPath: '/workspaces/$workspaceKey'
      preLoaderRoute: typeof WorkspacesWorkspaceKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EngineeringRouteChildren {
  EngineeringCheckpointsRoute: typeof EngineeringCheckpointsRoute
  EngineeringStagesRoute: typeof EngineeringStagesRoute
  EngineeringIndexRoute: typeof EngineeringIndexRoute
}

const EngineeringRouteChildren: EngineeringRouteChildren = {
  EngineeringCheckpointsRoute: EngineeringCheckpointsRoute,
  EngineeringStagesRoute: EngineeringStagesRoute,
  EngineeringIndexRoute: EngineeringIndexRoute,
}

const EngineeringRouteWithChildren = EngineeringRoute._addFileChildren(
  EngineeringRouteChildren,
)

interface InfrastructureRouteChildren {
  InfrastructureTopologyRoute: typeof InfrastructureTopologyRoute
  InfrastructureIndexRoute: typeof InfrastructureIndexRoute
}

const InfrastructureRouteChildren: InfrastructureRouteChildren = {
  InfrastructureTopologyRoute: InfrastructureTopologyRoute,
  InfrastructureIndexRoute: InfrastructureIndexRoute,
}

const InfrastructureRouteWithChildren = InfrastructureRoute._addFileChildren(
  InfrastructureRouteChildren,
)

interface OrganizationsRouteChildren {
  OrganizationsOrganizationIdRoute: typeof OrganizationsOrganizationIdRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
}

const OrganizationsRouteChildren: OrganizationsRouteChildren = {
  OrganizationsOrganizationIdRoute: OrganizationsOrganizationIdRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
}

const OrganizationsRouteWithChildren = OrganizationsRoute._addFileChildren(
  OrganizationsRouteChildren,
)

interface ProductsRouteChildren {
  ProductsProductKeyRoute: typeof ProductsProductKeyRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsProductKeyRoute: ProductsProductKeyRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ReleasesRouteChildren {
  ReleasesReleaseIdRoute: typeof ReleasesReleaseIdRoute
  ReleasesIndexRoute: typeof ReleasesIndexRoute
}

const ReleasesRouteChildren: ReleasesRouteChildren = {
  ReleasesReleaseIdRoute: ReleasesReleaseIdRoute,
  ReleasesIndexRoute: ReleasesIndexRoute,
}

const ReleasesRouteWithChildren = ReleasesRoute._addFileChildren(
  ReleasesRouteChildren,
)

interface RepositoriesRouteChildren {
  RepositoriesRepositoryIdRoute: typeof RepositoriesRepositoryIdRoute
  RepositoriesIndexRoute: typeof RepositoriesIndexRoute
}

const RepositoriesRouteChildren: RepositoriesRouteChildren = {
  RepositoriesRepositoryIdRoute: RepositoriesRepositoryIdRoute,
  RepositoriesIndexRoute: RepositoriesIndexRoute,
}

const RepositoriesRouteWithChildren = RepositoriesRoute._addFileChildren(
  RepositoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AiRoute: AiRoute,
  AssetsRoute: AssetsRoute,
  CommandRoute: CommandRoute,
  DecisionsRoute: DecisionsRoute,
  DocumentsRoute: DocumentsRoute,
  EngineeringRoute: EngineeringRouteWithChildren,
  ExecutiveRoute: ExecutiveRoute,
  InfrastructureRoute: InfrastructureRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OrganizationsRoute: OrganizationsRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  ReleasesRoute: ReleasesRouteWithChildren,
  RepositoriesRoute: RepositoriesRouteWithChildren,
  RoadmapsRoute: RoadmapsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  WorkspacesWorkspaceKeyRoute: WorkspacesWorkspaceKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
